[asio]
version="git" #(require)
type="lib" #lib(default) | bin | cmake
description="c++ asio network library" #(require)
module="asio::asio" #(require) if none_module=true -> no require
git="https://github.com/injae/asio.git" #(require)
branch="main" #(optional & require git)
#link=private #default
