[package]
name = "GTest"
# if you use git repo, package version is lastest
version = "lastest"
description = ""
global=true
# library name in cmake, cppm.toml use this value 
# [dependencies]
#${library_name} = {module =${value}}
cmake = {name = "gtest", findlib=""}
# write download value git or url
download = {git="https://github.com/google/googletest.git"}
#download = {url=""}
