[package]
    name = "GTest"
    version = "lastest"
    description = "Google c++ Testing library"
    cmake = {name = "gtest", findlib=""}
    download = {git="https://github.com/google/googletest.git"}
