[package]
name = "cpptoml"
# if you use git repo, package version is git
version = "git"
description = "cpptoml is a header-only library for parsing TOML use std::optional version"
global=false
# library name in cmake, cppm.toml use this value 
# [dependencies]
#${library_name} = {module =${value}}
cmake = {name = "cpptoml::cpptoml ", findlib=""}
# write download value git or url
download = {git="https://github.com/injae/cpptoml.git"}
#download = {url=""}
