[package]
name = "fmt"
# if you use git repo, package version is lastest
version = "lastest"
description = "c++ format library"
global=false
# library name in cmake, cppm.toml use this value 
# [dependencies]
#${library_name} = {module =${value}}
cmake = {name = "fmt::fmt", findlib=""}
# write download value git or url
download = {git="https://github.com/fmtlib/fmt.git"}
#download = {url=""}
