[package]
name = "fmt"
# if you use git repo, package version is lastest
version = "5.3.0"
description = "c++ format library"
global=false
# library name in cmake, cppm.toml use this value 
# [dependencies]
#${library_name} = {module =${value}}
cmake = {name = "fmt::fmt", findlib=""}
# write download value git or url
#download = {git=""}
download = {url="https://github.com/fmtlib/fmt/archive/5.3.0.tar.gz"}
[dependencies]
