[package]
    name     = "Boost"
    version  = "1.58.0"
    description = "Boost Library"
    cmake    = {name = "${Boost_LIBRARIES}", components="system filesystem"}
    download = {url="http://sourceforge.net/projects/boost/files/boost/1.58.0/boost_1_58_0.tar.gz"}