[package]
name = "ghcfilesystem"
# if you use git repo, package version is lastest
version = "git"
description = "An implementation of C++17 std::filesystem"
global=false
# library name in cmake, cppm.toml use this value 
# [dependencies]
#${library_name} = {module =${value}}
cmake = {name = "ghc_filesystem", findlib=""}
# write download value git or url
download = {git="https://github.com/gulrak/filesystem.git"}
#download = {url=""}
