[package]
name = "nlohmann_json"
# if you use git repo, package version is lastest
version = "lastest"
description = "JSON for Morden C++"
global=false
# library name in cmake, cppm.toml use this value 
# [dependencies]
#${library_name} = {module =${value}}
cmake = {name = "nlohmann_json::nlohmann_json", findlib=""}
# write download value git or url
download = {git="https://github.com/nlohmann/json.git"}
#download = {url=""}
[dependencies]
