[package]
name = "nlohmann_json"
# if you use git repo, package version is lastest
version = "git"
description = "JSON for Morden C++"
global=false
# library name in cmake, cppm.toml use this value 
# [dependencies]
#${library_name} = {module =${value}}
cmake = {name = "nlohmann_json::nlohmann_json", findlib=""}
# write download value git or url
download = {git="https://github.com/nlohmann/json.git"}
#download = {url=""}

[nlohmann_json]
version = "git"
description = "JSON for Morden C++"
module = "nlohmann_json::nlohmann_json"
# write download value git or url
git="https://github.com/nlohmann/json.git"