[hash-lib]
version="git" #(require)
type="lib" #lib(default) | bin | cmake
description="Portable C++ Hashing Library" #(require)
module="hash-lib::hash-lib " #(require) if none_module=true -> no require
git="https://github.com/injae/hash-library.git" #(require)
#branch="" #(optional & require git)
#link="public" #default
