[package]
name = "cpptoml"
# if you use git repo, package version is lastest
version = "0.1.1"
description = "c++ toml parsing library"
global=false
# library name in cmake, cppm.toml use this value 
# [dependencies]
#${library_name} = {module =${value}}
cmake = {name = "cpptoml", findlib=""}
# write download value git or url
#download = {git=""}
download = {url="https://github.com/skystrife/cpptoml/archive/v0.1.1.tar.gz"}
[dependencies]
