[package]
name = "ghcfilesystem"
# if you use git repo, package version is lastest
version = "1.2.4"
description = "An implementation of C++17 std::filesystem"
global=false
# library name in cmake, cppm.toml use this value 
# [dependencies]
#${library_name} = {module =${value}}
cmake = {name = "ghc_filesystem", findlib=""}
# write download value git or url
#download = {git=""}
download = {url="https://github.com/gulrak/filesystem/archive/v1.2.4"}
