[range-v3]
version = "0.11.0"
description = "Range library for C++14/17/20, basis for C++20's std::ranges"
module = "range-v3::range-v3"
url="https://github.com/ericniebler/range-v3/archive/refs/tags/0.11.0.zip"
flags="-DRANGE_V3_TESTS=OFF -DRANGE_V3_EXAMPLES=OFF -DRANGE_V3_PERF=OFF -DRANGE_V3_HEADER_CHECKS=OFF"