[package]
name = "oboe"
version = "git"
description = "Google Android Audio Library"
global=false
cmake = {name = "oboe", findlib=""}
download = {git="https://github.com/google/oboe.git"}
[dependencies]
