[package]
    name     = "nlpo"
    version  = "lastest"
    description = "c++ CLI Command and Option Library"
    cmake    = {name = "nlpo::nlpo"}
    download = {git="https://github.com/injae/nlpo.git"}