[package]
name = "nlpo"
# if you use git repo, package version is lastest
version = "lastest"
description = "program option library"
global=false
# library name in cmake, cppm.toml use this value 
# [dependencies]
#${library_name} = {module =${value}}
cmake = {name = "nlpo::nlpo", findlib=""}
# write download value git or url
download = {git="https://github.com/injae/nlpo.git"}
#download = {url=""}
