[package]
name = "FunctionalPlus"
# if you use git repo, package version is lastest
version = "git"
description = "Functional Programming Library for C++"
global=false
# library name in cmake, cppm.toml use this value 
# [dependencies]
#${library_name} = {module =${value}}
cmake = {name = "FunctionalPlus::fplus", findlib=""}
# write download value git or url
download = {git="https://github.com/Dobiasd/FunctionalPlus.git"}
#download = {url=""}
[dependencies]


[FunctionalPlus]
version = "git"
description = "Functional Programming Library for C++"
module = "FunctionalPlus::fplus"
git="https://github.com/Dobiasd/FunctionalPlus.git"