[package]
name = "range-v3"
# if you use git repo, package version is git
version = "git"
description = "c++ range library"
global=false
# library name in cmake, cppm.toml use this value 
# [dependencies]
#${library_name} = {module =${value}}
cmake = {name = "range-v3", findlib=""}
# write download value git or url
download = {git="https://github.com/ericniebler/range-v3.git"}
#download = {url=""}
