[package]
    name     = "Boost"
    version  = "1.65.1"
    description = "Boost Library"
    cmake    = {name = "${Boost_LIBRARIES}", components="system filesystem"}
    download = {url="https://dl.bintray.com/boostorg/release/1.65.1/source/boost_1_65_1.tar.gz"}