[spdlog]
version="1.8.2" #(require)
type="lib" #lib(default) | bin | cmake
description="c++ logging library" #(require)
module="spdlog::spdlog" #(require) if none_module=true -> no require
url="https://github.com/gabime/spdlog/archive/v1.8.2.zip" #(require)
#flags="-DSPDLOG_FMT_EXTERNAL=ON"
#branch="" #(optional & require git)
#link="public" #default
