[package]
name = "range-v3"
# if you use git repo, package version is git
version = "0.9.0"
description = "Range library for C++14/17/20, basis for C++20's std::ranges"
global=false
# library name in cmake, cppm.toml use this value 
# [dependencies]
#${library_name} = {module =${value}}
cmake = {name = "range-v3", findlib=""}
# write download value git or url
#download = {git=""}
download = {url="https://github.com/ericniebler/range-v3/archive/0.10.0.tar.gz"}

[range-v3]
version = "0.9.0"
description = "Range library for C++14/17/20, basis for C++20's std::ranges"
module = "range-v3"
url="https://github.com/ericniebler/range-v3/archive/0.9.0.tar.gz"